services:
  jobs:
    build: .
    container_name: tgfp-bin
    environment:
      - DOPPLER_TOKEN=<insert token>
      - DOPPLER_ENV=1
      - TZ=US/Pacific
    restart: unless-stopped
    volumes:
      - ./scripts:/scripts
      - ./data:/data
