services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=US/Pacific
    volumes:
      - $TGFP_HOME/nginx/conf:/etc/nginx/conf.d
      - $TGFP_HOME/nginx/cloudflare:/etc/cloudflare_certs
    ports:
      - "7443:443"
    depends_on:
      - tgfp-web
