services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=US/Pacific
    volumes:
      - $TGFP_HOME/nginx/nginx.conf:/etc/nginx/nginx.conf
      - tgfp_web_certbot_conf:/etc/letsencrypt
      - tgfp_web_certbot_www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tgfp-web
