services:
  tgfp-mongodb:
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    restart: unless-stopped
    container_name: tgfp-mongodb
    hostname: mongo
    ports:
      - "${MONGO_PORT_EXTERNAL}:${MONGO_PORT_INTERNAL}"
    volumes:
      - tgfp-db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:${MONGO_PORT_INTERNAL}/ --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  tgfp-create-picks:
    image: johnofcamas/tgfp-job-runner
    container_name: tgfp-create-picks
    environment:
      - TZ
      - HEALTHCHECK_BASE_URL
      - CREATE_PICKS_PAGE_TIME
      - MONGO_URI
      - CREATE_PICKS_HOUR
      - CREATE_PICKS_DAY_OF_WEEK
    restart: unless-stopped
    volumes:
      - $TGFP_HOME/create_picks/scripts:/app/scripts
    depends_on:
      tgfp-mongodb:
        condition: service_started
  tgfp-nag-players:
    image: johnofcamas/tgfp-job-runner
    container_name: tgfp-nag-players
    environment:
      - TZ
      - HEALTHCHECK_BASE_URL
      - MONGO_URI
      - DISCORD_AUTH_TOKEN
      - GUILD_NAME
      - GAME_START_DAY_OF_WEEK
      - GAME_START_TIME
    restart: unless-stopped
    volumes:
      - $TGFP_HOME/nag_players/scripts:/app/scripts
    depends_on:
      tgfp-mongodb:
        condition: service_started
  tgfp-update-scores:
    image: johnofcamas/tgfp-job-runner
    container_name: tgfp-update-scores
    environment:
      - TZ
      - HEALTHCHECK_BASE_URL
      - MONGO_URI
      - CREATE_PICKS_DAY_OF_WEEK
      - CREATE_PICKS_HOUR
    restart: unless-stopped
    volumes:
      - $TGFP_HOME/update_win_loss/scripts:/app/scripts
    depends_on:
      tgfp-mongodb:
        condition: service_started

  tgfp-db-backup:
    image: johnofcamas/tgfp-job-runner
    container_name: tgfp-db-backup
    environment:
      - TZ
      - BACKUP_DIR=/backup
      - HEALTHCHECK_BASE_URL
      - MONGO_HOST=mongo
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_PORT=$MONGO_PORT_EXTERNAL
      - DB_BACKUP_INTERVAL_MINUTES
    restart: unless-stopped
    volumes:
      - $TGFP_HOME/backup_db/scripts:/app/scripts
      - $MONGO_BACKUP_DIR:/backup
    depends_on:
      tgfp-mongodb:
        condition: service_started
  tgfp-web:
    image: johnofcamas/tgfp-web:latest
    container_name: tgfp-web
    restart: unless-stopped
    command: gunicorn -b 0.0.0.0:$WEB_PORT app:app
    environment:
      - TZ
      - LOG_LEVEL
      - OAUTHLIB_INSECURE_TRANSPORT
      - DISCORD_CLIENT_ID
      - DISCORD_REDIRECT_URI
      - DISCORD_CLIENT_SECRET
      - MONGO_URI
      - SECRET_KEY
    ports:
      - "$WEB_PORT:$WEB_PORT"
    depends_on:
      tgfp-mongodb:
        condition: service_started

volumes:
  tgfp-db:
    external: true
