services:
  tgfp-create-picks:
    image: johnofcamas/tgfp-job-runner
    environment:
      - DOPPLER_TOKEN=$DOPPLER_TOKEN
      - DOPPLER_ENV=1
      - TZ=US/Pacific
    restart: unless-stopped
    volumes:
      - $TGFP_HOME/create_picks/scripts:/app/scripts
    depends_on:
      tgfp-mongodb-prd:
        condition: service_healthy
